# Generated by Django 3.0.6 on 2020-06-08 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='bar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Created_at')),
                ('last_modified_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Last_modified_at')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('capacidad', models.IntegerField(default=0, verbose_name='Capacidad')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bars_bar_created', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bars_bar_lastmodified', to=settings.AUTH_USER_MODEL, verbose_name='last_modified_by')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
