# Generated by Django 3.0.6 on 2020-06-06 18:46

import Cerveza.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='cerveza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Created_at')),
                ('last_modified_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Last_modified_at')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('abv', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Alcohol by volume')),
                ('color', models.PositiveSmallIntegerField(choices=[(1, 'Yellow'), (2, 'Amber'), (3, 'Brown'), (4, 'Black')], default=1, verbose_name='Color')),
                ('is_filtered', models.BooleanField(default=False, verbose_name='Is filtered?')),
                ('image', models.ImageField(blank=True, null=True, upload_to=Cerveza.utils.image_upload_location, verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Cerveza',
                'verbose_name_plural': 'Cervezas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='specialIngridients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Created_at')),
                ('last_modified_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Last_modified_at')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('cerveza', models.ManyToManyField(blank=True, related_name='especial_cerveza_ingredients', to='Cerveza.cerveza')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cerveza_specialingridients_created', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cerveza_specialingridients_lastmodified', to=settings.AUTH_USER_MODEL, verbose_name='last_modified_by')),
            ],
            options={
                'verbose_name': 'Ingrediente_Especial',
                'verbose_name_plural': 'Ingredientes_Especiales',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='compañia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Created_at')),
                ('last_modified_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Last_modified_at')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cerveza_compañia_created', to=settings.AUTH_USER_MODEL, verbose_name='created_by')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cerveza_compañia_lastmodified', to=settings.AUTH_USER_MODEL, verbose_name='last_modified_by')),
            ],
            options={
                'verbose_name': 'Compañia',
                'verbose_name_plural': 'Compañias',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='cerveza',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cervezas', to='Cerveza.compañia'),
        ),
        migrations.AddField(
            model_name='cerveza',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cerveza_cerveza_created', to=settings.AUTH_USER_MODEL, verbose_name='created_by'),
        ),
        migrations.AddField(
            model_name='cerveza',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cerveza_cerveza_lastmodified', to=settings.AUTH_USER_MODEL, verbose_name='last_modified_by'),
        ),
    ]
