# Generated by Django 3.0.6 on 2020-06-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cerveza', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compañia',
            name='tax_number',
            field=models.IntegerField(default=7, verbose_name='Tax Number'),
            preserve_default=False,
        ),
    ]
