# Generated by Django 3.0.6 on 2020-06-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cerveza', '0002_compañia_tax_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compañia',
            name='tax_number',
            field=models.IntegerField(auto_created=True, max_length=5, verbose_name='Tax_Number'),
        ),
    ]
