# Generated by Django 3.0.6 on 2020-06-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cerveza', '0005_remove_compañia_tax_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='compañia',
            name='tax_number',
            field=models.IntegerField(auto_created=True, default=9, max_length=5, unique=True, verbose_name='Tax_Number'),
            preserve_default=False,
        ),
    ]
