# Generated by Django 3.0.6 on 2020-06-08 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cerveza', '0006_compañia_tax_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compañia',
            name='tax_number',
        ),
    ]
