# Generated by Django 3.0.6 on 2020-06-08 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cerveza', '0007_remove_compañia_tax_number'),
    ]

    operations = [

    ]
