# Generated by Django 3.0.6 on 2020-06-08 22:11
import random

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('Cerveza', '0008_auto_20200609_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='compañia',
            name='tax_number',
            field=models.IntegerField(default=7, max_length=5, blank=True, null=True, verbose_name='Tax_Number'),
            preserve_default=False,
        ),
    ]
