# Generated by Django 3.0.6 on 2020-06-08 22:16
import random


from django.db import migrations

def gen_tax_number(apps, schema_editor):
    MyModel = apps.get_model('Cerveza', 'compañia')
    for row in MyModel.objects.all():
        row.tax_number = random.randint(1,1000)
        row.save(update_fields=['tax_number'])

class Migration(migrations.Migration):

    dependencies = [
        ('Cerveza', '0009_compañia_tax_number'),
    ]

    operations = [
        migrations.RunPython(gen_tax_number, reverse_code=migrations.RunPython.noop)
    ]
